name: Continious Integration
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    container: node:12-alpine
    steps:
      - uses: actions/checkout@v1
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: Check if all files follow prettier codestyles
        run: yarn format:check
  tests:
    runs-on: ubuntu-latest
    container: node:12-alpine
    steps:
      - uses: actions/checkout@v1
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: Run tests
        run: yarn test
